name: Publish project to Maven repository
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and cache Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Set up gradle.properties
        env:
          GOOGLE_PROPERTIES_BASE64_PROPERTIES: ${{ secrets.GOOGLE_PROPERTIES_BASE64_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "$GOOGLE_PROPERTIES_BASE64_PROPERTIES" > ~/.gradle/gradle.properties.b64
          base64 -d -i gradle.properties > ~/.gradle/gradle.properties
        
      - name: Check gradle.properties
        run: cat ~/.gradle/gradle.properties
        
      - name: Publish with Gradle
        run: ./gradlew publishReleasePublicationToCexupRepository
