name: Publish project to Maven repository
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
      - name: Set up gradle.properties
        shell: bash
        run: |
          echo android.useAndroidX=true > ./gradle.properties
          echo kotlin.code.style=official > ./gradle.properties
          echo android.nonTransitiveRClass=true > ./gradle.properties
          echo ENDPOINT_JVM_REPOSITORY=\"$ENDPOINT_JVM_REPOSITORY\" > ./gradle.properties
          echo JVM_REPOSITORY_USERNAME=\"$JVM_REPOSITORY_USERNAME\" > ./gradle.properties
          echo JVM_REPOSITORY_TOKEN=\"$JVM_REPOSITORY_TOKEN\" > ./gradle.properties
      - name: Publish with Gradle
        run: ./gradlew publishReleasePublicationToMavenRepository
